/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.2 ./public/models/Fish/Fish.glb 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Fish(props) {
  const { nodes, materials } = useGLTF('./models/Fish/Fish.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Goldfish_01_Cube058_1.geometry} material={materials.FF5722} />
      <mesh geometry={nodes.Goldfish_01_Cube058_1_1.geometry} material={materials['1A1A1A']} />
      <mesh geometry={nodes.Goldfish_01_Cube058_1_2.geometry} material={materials.FFEB3B} />
    </group>
  )
}

useGLTF.preload('./models/Fish/Fish.glb')
